URL = 'http://demoapp-test.cloudapps.ocp-tdemo.teco.prd.a.tecdomain.net/#/'
USERNAME_A = 'admin'
PWD_A = 'admin'
BROWSER = 'Firefox'
USERNAME_TEST = 'foxuser'
PWD_TEST = 'testipassu'
EMAIL = 'foxuser@tecdomain.net'