URL = 'http://demoapp-test.cloudapps.ocp-tdemo4.teco.prd.a.tecdomain.net/#/'
USERNAME_A = 'admin'
PWD_A = 'admin'
BROWSER = 'GoogleChrome'
USERNAME_TEST = 'chromeuser'
PWD_TEST = 'testipassu'
EMAIL = 'chromeuser@tecdomain.net'
